FROM eclipse-temurin:20-jdk-alpine
WORKDIR /app

# Copy the already-built JAR
COPY target/Court_Booking-0.0.1-SNAPSHOT.jar app.jar

# Create H2 file storage folder
RUN mkdir -p /app/data

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app/app.jar"]
